import { Inter } from "next/font/google";

import "./globals.css";

import type { JSX, PropsWithChildren } from "react";
import type { NextFont } from "next/dist/compiled/@next/font";
import type { Metadata } from "next";

const inter: NextFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: PropsWithChildren): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
